#!/usr/bin/env bash
#
# Rewrite conf.d/cloudflare.conf from Cloudflare's published ranges.
#
# Two jobs, both of which break quietly when the list goes stale:
#
#   set_real_ip_from   restores the visitor's address. Without it every request
#                      arrives from Cloudflare, and every per-IP limiter in the
#                      app — sign-in codes, votes, submissions — is counting one
#                      shared bucket instead of one per person.
#   $from_cloudflare   marks requests that did not come through Cloudflare, so
#                      the server blocks can drop them. With TLS terminated at
#                      the edge, that check is what stops anyone who learns this
#                      machine's address from talking to it in the clear.
#
# Cloudflare adds ranges occasionally. Run this after that happens, or from cron
# monthly; it only writes when something changed, and only reloads nginx when it
# wrote. https://www.cloudflare.com/ips/
#
set -euo pipefail

target="${1:-/etc/nginx/conf.d/cloudflare.conf}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

v4="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v6)"

# A truncated answer would lock the site out of its own front door, so refuse
# anything that does not look like the real list.
[ "$(printf '%s\n' "$v4" | grep -c '/')" -ge 10 ] || { echo "ipv4 list looks wrong" >&2; exit 1; }
[ "$(printf '%s\n' "$v6" | grep -c '/')" -ge 5 ] || { echo "ipv6 list looks wrong" >&2; exit 1; }

{
  echo "# Generated by deploy/nginx/refresh-cloudflare-ips.sh on $(date -u +%F). Do not edit."
  echo
  printf '%s\n' "$v4" "$v6" | grep '/' | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo "# The header Cloudflare puts the visitor's address in. Single-valued, so"
  echo "# there is no chain to walk and real_ip_recursive has nothing to do."
  echo "real_ip_header CF-Connecting-IP;"
  echo
  echo "# Evaluated against the address nginx actually accepted the connection"
  echo "# from — \$remote_addr has been rewritten by the time anything reads it."
  echo "geo \$realip_remote_addr \$from_cloudflare {"
  echo "    default 0;"
  echo
  echo "    # The machine itself: health checks, and the frontend's own"
  echo "    # server-side fetches when api.lobbyhub.gg is pinned to loopback."
  echo "    127.0.0.1/32 1;"
  echo "    ::1/128      1;"
  echo
  printf '%s\n' "$v4" "$v6" | grep '/' | sed 's/^/    /; s/$/ 1;/'
  echo "}"
} > "$tmp"

if [ -f "$target" ] && diff -q <(tail -n +2 "$target") <(tail -n +2 "$tmp") > /dev/null; then
  echo "Cloudflare ranges unchanged."
  exit 0
fi

install -m 0644 "$tmp" "$target"
nginx -t && systemctl reload nginx
echo "Wrote $target and reloaded nginx."
