import type { Metadata } from 'next'
import Link from 'next/link'
import { Suspense } from 'react'
import { GameCard } from '@/components/game-card'
import { Icon } from '@/components/icons'
import { ServerSection } from '@/components/server-section'
import type { Game } from '@/lib/api'
import { getGames, searchServers } from '@/lib/data'
import { canonical } from '@/lib/seo'

type Search = Promise<{ q?: string }>

/**
 * Indexable with no term, never with one.
 *
 * The bare page is a real catalog entry point worth having in the index. Every
 * ?q= variant is a thin page generated by whoever typed it, and letting those be
 * indexed is how a catalog domain fills the index with its own near-duplicates.
 * `follow` stays on either way, so servers found here still pass link value to
 * their own pages.
 */
export async function generateMetadata({
  searchParams,
}: {
  searchParams: Search
}): Promise<Metadata> {
  const term = (await searchParams).q?.trim() ?? ''

  if (term === '') {
    return {
      title: 'All game servers',
      description:
        'Every server on LobbyHub, busiest first — across Rust, Minecraft, Counter-Strike 2, DayZ and more.',
      ...canonical('/search'),
    }
  }

  return {
    title: `Search: ${term}`,
    description: `Game servers matching “${term}” on LobbyHub.`,
    robots: { index: false, follow: true },
  }
}

/**
 * Search results, and the browsable "all servers" listing when there is no term
 * — the destination behind every "View all servers" on the home page.
 *
 * The shell is static and the answer is streamed into it. That split is forced
 * by cacheComponents (a search for an arbitrary term cannot be cached, and
 * uncached data outside Suspense would block the whole route) but it is also
 * the right shape: the heading and the search box are useful the moment they
 * arrive, and they are what somebody who mistyped needs first.
 */
export default function SearchPage({ searchParams }: { searchParams: Search }) {
  return (
    <div className="space-y-8">
      <nav aria-label="Breadcrumb" className="text-xs text-subtle">
        <Link href="/" className="hover:text-fg">
          LobbyHub
        </Link>
        <span className="mx-1.5">/</span>
        <span className="text-muted">Search</span>
      </nav>

      <Suspense fallback={<ResultsSkeleton />}>
        <Results searchParams={searchParams} />
      </Suspense>
    </div>
  )
}

async function Results({ searchParams }: { searchParams: Search }) {
  const term = (await searchParams).q?.trim() ?? ''

  const [servers, games] = await Promise.all([
    searchServers(term, 24),
    // Matching a game by name is what makes "rust" find the game page and not
    // only the servers whose name happens to contain the word. The catalog is
    // 27 rows and already cached, so this is a filter, not another request.
    term === '' ? Promise.resolve([] as Game[]) : getGames().catch(() => [] as Game[]),
  ])

  const matchedGames = term === '' ? [] : matchGames(games, term)

  return (
    <div className="space-y-8">
      <header className="space-y-2">
        <h1 className="font-display text-2xl font-black tracking-tight uppercase sm:text-3xl">
          {term === '' ? 'All game servers' : `Search: ${term}`}
        </h1>
        {term !== '' && (
          <p className="text-sm text-subtle">
            {servers.length === 0
              ? 'No servers matched.'
              : `${servers.length} server${servers.length === 1 ? '' : 's'} matched.`}
          </p>
        )}
      </header>

      <SearchForm term={term} />

      {matchedGames.length > 0 && (
        <section aria-labelledby="search-games" className="space-y-4">
          <h2 id="search-games" className="font-display text-xl font-black tracking-tight uppercase">
            Games
          </h2>
          <ul className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">
            {matchedGames.map((game) => (
              <li key={game.slug}>
                <GameCard game={game} href={`/games/${game.slug}`} />
              </li>
            ))}
          </ul>
        </section>
      )}

      <ServerSection
        title={term === '' ? 'Servers' : 'Matching servers'}
        servers={servers}
        viewAllHref={term === '' ? undefined : '/search'}
        viewAllLabel="Browse all servers"
      />

      {servers.length === 0 && matchedGames.length === 0 && (
        <div className="rounded-xl border border-line bg-surface px-4 py-12 text-center">
          <p className="text-muted">
            {term === ''
              ? 'No servers are listed yet.'
              : `Nothing matched “${term}”. Try a server name, a game, or an address.`}
          </p>
          <Link
            href="/games"
            className="mt-3 inline-block text-sm font-medium text-brand hover:underline"
          >
            Browse servers by game
          </Link>
        </div>
      )}
    </div>
  )
}

/**
 * The box, restated on the results page.
 *
 * Somebody who landed here on an empty result needs it in front of them, not up
 * in the chrome. Same plain GET as the home page, so it still works with
 * JavaScript off.
 */
function SearchForm({ term }: { term: string }) {
  return (
    <form role="search" action="/search" method="get" className="flex flex-col gap-2 sm:flex-row">
      <div className="relative min-w-0 flex-1">
        <label htmlFor="search-again" className="sr-only">
          Search servers by name, game or address
        </label>
        <span aria-hidden className="absolute top-1/2 left-4 -translate-y-1/2 text-subtle">
          <Icon.search className="size-5" />
        </span>
        <input
          id="search-again"
          name="q"
          type="search"
          defaultValue={term}
          autoComplete="off"
          placeholder="Search servers by name, game or address"
          className="w-full rounded-xl border border-line bg-surface py-3.5 pr-4 pl-11 outline-none transition-colors placeholder:text-subtle focus:border-brand"
        />
      </div>
      <button
        type="submit"
        className="shrink-0 cursor-pointer rounded-xl bg-brand px-6 py-3.5 font-medium text-white transition-colors hover:bg-brand-strong"
      >
        Search
      </button>
    </form>
  )
}

/** Reserves the height the answer will take, so its arrival does not shift the page. */
function ResultsSkeleton() {
  return (
    <div className="space-y-8" aria-hidden>
      <div className="h-9 w-64 animate-pulse rounded bg-surface" />
      <div className="h-14 animate-pulse rounded-xl bg-surface" />
      <ul className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
        {Array.from({ length: 8 }, (_, index) => (
          <li key={index} className="h-44 animate-pulse rounded-xl bg-surface" />
        ))}
      </ul>
    </div>
  )
}

/** Name, short name and aliases — the same haystack the API's own search uses. */
function matchGames(games: Game[], term: string): Game[] {
  const needle = term.toLowerCase()

  return games
    .filter((game) =>
      [game.name, game.short_name ?? '', ...(game.aliases ?? [])]
        .filter(Boolean)
        .some((candidate) => candidate.toLowerCase().includes(needle)),
    )
    .slice(0, 4)
}
